### ISSUE TITLE
Need guide about contributing

### ISSUE THREAD

**Issue by dutchiexl** [webflo/packagist#7]
Sometimes I hit a wrong configured package, or a package is missing. Would contributers be able to add and change these ? Is it possible to add a "guide" here somewhere ?

**Comment by kasperg** [comment]
If a package is missing or misconfigured it is probably due to a bug in the project.

Unlike packagist.org this fork retrieves projects from drupal.org using the API and exposes them as Composer packages. Contributors should only need to worry about getting their projects on drupal.org.

There are probably a lot of edge cases so getting a list of problematic projects would be a great start.

**Comment by derhasi** [comment]
@dutchiexl, currently there might be multiple reasons for missing or misconfigured packages. So collecting all of those would be a large help, so we might find more edge cases.

We might add functionality to the project in the future, so a composer.json within a drupal project may be recognized and can override some or all auto-generated information.

I try to add some information to the README soon.

**Comment by derhasi** [comment]
I added the issue in drupal-composer/drupal-packagist. So we could close this here :)

**Comment by webflo** [comment]
This issue was moved to drupal-composer/drupal-packagist#7
